Main
team-gleam/kiwi-basket pull request #12
Opened 2020-05-23 01:18 UTC by 4afS

- 設定ファイルのフォーマットを定義
- ルーターの定義
- 自動マイグレーションの追加
- MySQLのオプションを追加
- ポート番号の変更
- methodの追加
- その他修正

2020-05-23 12:19 UTC, blackbracken commented on .gitignore
> +config.yaml
`yml`のtypoかなと思って調べてみたらどうやら`yaml`とする宗派もあるらしい

2020-05-23 12:35 UTC, blackbracken requested changes
Otherwise LGTM

2020-05-23 12:35 UTC, blackbracken commented on infra/db/task/task.go
> +type TaskDB struct {
gormとかの風習を読めていないからそれに沿っているなら読み飛ばしてほしいんだけれど, `TaskRecord`とかの方が明確かも

2020-05-23 12:35 UTC, blackbracken commented on infra/db/task/task.go
> +func transformTaskForDB(t taskModel.Task, u username.Username) TaskDB {
`TaskDB`の名前を変えるようであれば`createRecord`/`toRecord`とかでもいいかも

2020-05-23 12:35 UTC, blackbracken commented on usecase/timetables/timetables.go
>  	credentialed, err := u.credentialUsecase.IsCredentialed(token)
`HasCredential`の方が個人的に好き, これ前のレビュー漏れだと思う🥺

2020-05-23 17:04 UTC, 4afS commented on infra/db/task/task.go
> +type TaskDB struct {
確かに，そのほうがわかりやすそう．他の~DBも含め修正します．

これ疑問なんだけど，Modelと名前かぶるから良くないかなと思ってTaskDBにしてるんだけどTaskにしてもいいのかな？

2020-05-24 14:26 UTC, blackbracken commented on infra/db/task/task.go
> +type TaskDB struct {
それが適切なら良いと思う, そのための名前空間だろうしね

2020-05-24 20:40 UTC, 4afS commented on infra/db/task/task.go
> +type TaskDB struct {
変更しました！

2020-05-24 20:42 UTC, 4afS commented on infra/db/task/task.go
> +func transformTaskForDB(t taskModel.Task, u username.Username) TaskDB {
`toRecord` / `fromRecord` に変更しました！

2020-05-24 20:44 UTC, 4afS commented on usecase/timetables/timetables.go
>  	credentialed, err := u.credentialUsecase.IsCredentialed(token)
`HasCredential` に変更しました！

2020-05-24 20:45 UTC, 4afS commented on .gitignore
> +config.yaml
`yml` も念の為追加しておいた

2020-05-24 20:49 UTC, blackbracken approved these changes
LGTM

2020-05-24 20:49 UTC, merged